name: lvweixishun
on:
  workflow_dispatch:

  schedule:
    - cron: '57 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lvweixishun
        env:
          yzd5: ${{ secrets.yzd5 }}
        run: |
          printf '%s' "$yzd5" | jq -r .btpc26688 | /bin/bash
          echo $mrx13162 | jq -r .lctv0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qDZvJVKl
          path: "*.zip"
          retention-days: 1
